### ISSUE TITLE
Does not work when moving between sections

### ISSUE THREAD

**Issue by agovorukhin** [KyoheiG3/TableViewDragger#14] opened 2018-03-07 17:46 UTC
libc++abi.dylib: terminating with uncaught exception of type NSException

The application crashes when moving between sections

**Comment by KyoheiG3** [comment] 2018-03-08 00:57
Hi @Qumonking 
Should check https://github.com/KyoheiG3/TableViewDragger/blob/master/TableViewDraggerExample/TableViewDraggerExample/TableViewController.swift.
It does not crash when moving between sections.

**Comment by agovorukhin** [comment] 2018-03-08 04:40
Video -> https://yadi.sk/i/qXfTQn6d3T95Aw
[UITableViewController.txt](https://github.com/KyoheiG3/TableViewDragger/files/1791848/123.txt)

If there are no elements in the section, then moving to other sections is not possible at all

**Comment by KyoheiG3** [comment] 2018-03-08 06:15
I tried it, then it succeeded. Please make sure your `TagsTableViewController`.
I think that it has not changed elements in the delegate function.
For example, should try to change the element like following:
```
func dragger(_ dragger: TableViewDragger, moveDraggingAt indexPath: IndexPath, newIndexPath: IndexPath) -> Bool {
    let item = arrSect[indexPath.section][indexPath.row]
    arrSect[indexPath.section].remove(at: indexPath.row)
    arrSect[newIndexPath.section].insert(item, at: newIndexPath.row)

    tableView.moveRow(at: indexPath, to: newIndexPath)

    return true
}
```

**Comment by agovorukhin** [comment] 2018-03-08 07:49
@KyoheiG3 It work!) But it does not work if there are no cells in the section, I can not move the cell there
video -> https://yadi.sk/i/3zN3FwDK3T9L3s

**Comment by KyoheiG3** [comment] 2018-03-08 10:27
I confirmed that. It has to improve :( Thanks.

**Comment by agovorukhin** [comment] 2018-03-08 14:22
@KyoheiG3 Will you fix this in the future?

**Comment by KyoheiG3** [comment] 2018-03-09 04:53
I may try it, but it is not so easy. So do not expect too much.

**Comment by agovorukhin** [comment] 2018-03-09 05:54
@KyoheiG3 Well, I will follow the updates. This is a very useful function

**Comment by KyoheiG3** [comment] 2018-03-12 02:06
@Qumonking Fixed in #15 and released 1.1.1. Try it.

**Comment by agovorukhin** [comment] 2018-03-12 06:07
@KyoheiG3 It works, but there are bugs that can be seen on the video. The phone hangs and the video is not recorded fully, the point is that when you move from the bottom, everything starts jumping up and down. Try to repeat this with a lot of elements, you will understand what I'm talking about.
[video](https://yadi.sk/i/yNEHqmmi3TFyYq).

**Comment by KyoheiG3** [comment] 2018-03-12 06:27
@Qumonking is it iOS11? How is iOS10?

**Comment by agovorukhin** [comment] 2018-03-12 08:53
@KyoheiG3 It is IOS 11

**Comment by KyoheiG3** [comment] 2018-03-15 02:31
@Qumonking I understood the cause. But, it could not improve the issue, although I tried to resolve.
If you return following delegate function, the issue appears.
```
func tableView(_ tableView: UITableView, estimatedHeightForRowAt indexPath: IndexPath) -> CGFloat
```
So, could you delete the delegate function and set 0 or `UITableViewAutomaticDimension` to `estimatedRowHeight` of the `tableView`? Otherwise, I could not improve it.

**Comment by agovorukhin** [comment] 2018-03-15 10:32
@KyoheiG3 It did not solve my problem. Cells still jump up and down

**Comment by KyoheiG3** [comment] 2018-03-16 01:28
If you used iOS11, it can solve at only `0`.
I made example branch. Could you check it?
https://github.com/KyoheiG3/TableViewDragger/tree/fix-jumping-cell

There are 2 ViewController.
The difference is whether `func tableView(_ tableView: UITableView, estimatedHeightForRowAt indexPath: IndexPath) -> CGFloat` exists.

**Comment by Qumonking** [comment] 2018-03-16 09:11
@KyoheiG3 I did not quite understand what needs to be changed.

**Comment by Qumonking** [comment] 2018-03-17 13:45
@KyoheiG3 This works, but when moving between sections with many elements, jumps are noticeable

**Comment by agovorukhin** [comment] 2018-03-17 13:48
@KyoheiG3 It works!
```
viewDidLoad
tableView.estimatedRowHeight = 0

    override func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return 100
    }
```

Thanks you!

**Closed as completed** 2018-03-17 13:49 UTC
Labels: enhancement
